# **DATA 311 UBCO, Logistic Regression implemented in Python**

## **Assignment 2, Logistic Classification:**

### **Logistic Model Implementation:**

In [31]:
##decleration & data first as always

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt
import statsmodels.api as sm
# import statsmodels.formula.api as smf
# from sklearn.neighbors import KNeighborsRegressor
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.model_selection import GridSearchCV
# from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix

df = pd.read_csv('myopiacomma.csv')
df.head(10)

ID  STUDYYEAR  MYOPIC  AGE  GENDER  SPHEQ     AL    ACD     LT    VCD  \
0   1       1992       1    6       1 -0.052  21.89  3.690  3.498  14.70   
1   2       1995       0    6       1  0.608  22.38  3.702  3.392  15.29   
2   3       1991       0    6       1  1.179  22.49  3.462  3.514  15.52   
3   4       1990       1    6       1  0.525  22.20  3.862  3.612  14.73   
4   5       1995       0    5       0  0.697  23.29  3.676  3.454  16.16   
5   6       1995       0    6       0  1.744  22.14  3.224  3.556  15.36   
6   7       1993       0    6       1  0.683  22.33  3.186  3.654  15.49   
7   8       1991       0    6       1  1.272  22.39  3.732  3.584  15.08   
8   9       1991       0    7       0  1.396  22.62  3.464  3.408  15.74   
9  10       1991       0    6       1  0.972  22.74  3.504  3.696  15.54   

   SPORTHR  READHR  COMPHR  STUDYHR  TVHR  DIOPTERHR  MOMMY  DADMY  
0       45       8       0        0    10         34      1      1  
1        4       0       1        1     7         12      1      1  
2       14       0       2        0    10         14      0      0  
3       18      11       0        0     4         37      0      1  
4       14       0       0        0     4          4      1      0  
5       10       6       2        1    19         44      0      1  
6       12       7       2        1     8         36      0      1  
7       12       0       0        0     8          8      0      0  
8        4       0       3        1     3         12      0      0  
9       30       5       1        0    10         27      0      0

In [ ]:
df.describe()

In [ ]:
df = df.dropna()

df.describe()

In [33]:
df['PARENTMY'] = (df['MOMMY'] | df['DADMY']).astype(int)

# df.head(10)

df.columns

Index(['ID', 'STUDYYEAR', 'MYOPIC', 'AGE', 'GENDER', 'SPHEQ', 'AL', 'ACD',
       'LT', 'VCD', 'SPORTHR', 'READHR', 'COMPHR', 'STUDYHR', 'TVHR',
       'DIOPTERHR', 'MOMMY', 'DADMY', 'PARENTMY'],
      dtype='object')

### **Split into a training & testing as always:**

In [34]:
n = df.shape[0]
i = np.random.permutation(n)

train_size = round(0.6*n)
test_size = n - train_size

train = i[:train_size]
test = i[:test_size]

training_data = df.iloc[train]
testing_data = df.iloc[test]

training_data.columns

Index(['ID', 'STUDYYEAR', 'MYOPIC', 'AGE', 'GENDER', 'SPHEQ', 'AL', 'ACD',
       'LT', 'VCD', 'SPORTHR', 'READHR', 'COMPHR', 'STUDYHR', 'TVHR',
       'DIOPTERHR', 'MOMMY', 'DADMY', 'PARENTMY'],
      dtype='object')

### **Now we fit the Logistic Regression:**

to do this think back to sm.OLS from part 1

    A regular Linear Model is made with sm.OLS(y, sm.add_constant(x)).fit()
    & the Logit Model we want here is made by sm.OLS(y, sm.add_constant(x)).fit()

In [54]:
x_train_1 = training_data[['SPHEQ', 'AL', 'ACD']]
y_train_1 = training_data['MYOPIC']
x_test_1 =  testing_data[['MYOPIC', 'SPHEQ', 'AL', 'ACD']]
y_test_1 =  testing_data['MYOPIC']

LogModel_1 = sm.Logit(y_train_1, sm.add_constant(x_train_1)).fit()

Optimization terminated successfully.
         Current function value: 0.260519
         Iterations 8


In [55]:
x_train_2 = training_data[['SPHEQ', 'AL', 'ACD', 'PARENTMY']]
y_train_2 = training_data['MYOPIC']
x_test_2 =  testing_data[['MYOPIC', 'SPHEQ', 'AL', 'ACD', 'PARENTMY']]
y_test_2 =  testing_data['MYOPIC']

LogModel_2 = sm.Logit(y_train_2, sm.add_constant(x_train_2)).fit()

Optimization terminated successfully.
         Current function value: 0.254307
         Iterations 8


In [56]:
x_train_3 = training_data[['SPHEQ', 'AL', 'ACD', 'PARENTMY', 'READHR', 'COMPHR', 'TVHR']]
y_train_3 = training_data['MYOPIC']
x_test_3 =  testing_data[['MYOPIC', 'SPHEQ', 'AL', 'ACD', 'PARENTMY', 'READHR', 'COMPHR', 'TVHR']]
y_test_3 =  testing_data['MYOPIC']

LogModel_3 = sm.Logit(y_train_3, sm.add_constant(x_train_3)).fit()

Optimization terminated successfully.
         Current function value: 0.251258
         Iterations 8


### **Things to do with the Logistic Regression Model Objects:**

    use LogitModel.summary() or LogitModel.summary2() for a summary

In [57]:
LogModel_1.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                         Results: Logit
=================================================================
Model:              Logit            Method:           MLE       
Dependent Variable: MYOPIC           Pseudo R-squared: 0.314     
Date:               2024-01-01 16:41 AIC:              201.3050  
No. Observations:   371              BIC:              216.9698  
Df Model:           3                Log-Likelihood:   -96.652   
Df Residuals:       367              LL-Null:          -140.99   
Converged:          1.0000           LLR p-value:      4.2051e-19
No. Iterations:     8.0000           Scale:            1.0000    
-------------------------------------------------------------------
           Coef.    Std.Err.      z      P>|z|     [0.025    0.975]
-------------------------------------------------------------------
const      7.6655     6.8341    1.1217   0.2620   -5.7291   21.0602
SPHEQ     -4.0812     0.5703   -7.1559   0.0000   -5.1991   -2.9634
AL        -0.3594     0.3358   -1.0701   0.2846   -1.0176    0.2988
ACD        0.1657     0.9434    0.1756   0.8606   -1.6834    2.0148
=================================================================

"""

    or use LogitModel.params to gather the coefficients directly

In [58]:
# LogModel_1.params

print(LogModel_1.params, "\n\n", LogModel_2.params, "\n\n", LogModel_3.params)

const    7.665540
SPHEQ   -4.081244
AL      -0.359391
ACD      0.165692
dtype: float64 

 const       5.158360
SPHEQ      -4.030973
AL         -0.292686
ACD         0.161451
PARENTMY    1.178246
dtype: float64 

 const       6.136764
SPHEQ      -4.094814
AL         -0.313863
ACD         0.170293
PARENTMY    1.193641
READHR     -0.065791
COMPHR     -0.036856
TVHR       -0.025164
dtype: float64


### **Time to find the accuracy:**

this time we will use the confusion matrix instead of just an accuracy stat

In [60]:
# pred1 = LogModel_1.predict(x_test_1)

# # x_test_1_reshaped = np.array(x_test_1).reshape(1, -1)
# # pred1 = LogModel_1.predict(x_test_1_reshaped)

# y1 = (pred1 >= 0.5).astype(int)
# cm1 = confusion_matrix(y_test_1, y1)

# print(x_test_1.shape)  # Check the shape of x_test_1
# print(LogModel_1.params.shape)  # Check the shape of the model's coefficients

pred1 = LogModel_1.predict(x_test_1)
y1 = (pred1 >= 0.5).astype(int)
cm1 = confusion_matrix(y_test_1, y1)
cm1



array([[214,   0],
       [ 20,  13]], dtype=int64)

In [61]:
pred2 = LogModel_2.predict(x_test_2)
y2 = (pred2 >= 0.5).astype(int)
cm2 = confusion_matrix(y_test_2, y2)
cm2

array([[214,   0],
       [ 19,  14]], dtype=int64)

In [62]:
pred3 = LogModel_3.predict(x_test_3)
y3 = (pred3 >= 0.5).astype(int)
cm3 = confusion_matrix(y_test_3, y3)
cm3

array([[214,   0],
       [ 20,  13]], dtype=int64)